/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { InteractiveSlide, QuizQuestion } from './types';

export const SLIDES_DATA: InteractiveSlide[] = [
  {
    id: 'welcome',
    type: 'welcome',
    title: 'Quinti! 🌟',
    subtitle: 'Sorria, você está aprendendo! 😄',
    description: 'Boas-vindas à nossa English Class!',
    colorTheme: 'from-amber-400 to-orange-500',
  },
  {
    id: 'greetings',
    type: 'greetings',
    title: '1. Hello! Como cumprimentar?',
    subtitle: 'Greetings & Phrases 🗣️',
    description: 'Clique nas frases para ouvir o som e aprender como falar inglês legal!',
    colorTheme: 'from-blue-400 to-indigo-600',
    vocabList: [
      { english: 'Hello!', portuguese: 'Olá / Oi!', icon: '👋' },
      { english: 'Good morning!', portuguese: 'Bom dia!', icon: '☀️' },
      { english: 'Good afternoon!', portuguese: 'Boa tarde!', icon: '🌤️' },
      { english: 'What is your name?', portuguese: 'Qual é o seu nome?', icon: '🤔' },
      { english: 'My name is...', portuguese: 'Meu nome é...', icon: '🧑' },
      { english: 'Thank you!', portuguese: 'Obrigado!', icon: '🙏' },
      { english: 'Goodbye!', portuguese: 'Tchau!', icon: '🏃' },
    ],
  },
  {
    id: 'colors',
    type: 'colors',
    title: '2. The Magic Rainbow 🌈',
    subtitle: 'Let\'s Learn Colors! 🎨',
    description: 'Selecione uma cor para pintar o mundo e ouvir a pronúncia!',
    colorTheme: 'from-emerald-400 to-green-600',
    vocabList: [
      { english: 'Red', portuguese: 'Vermelho', icon: '🔴', color: 'bg-red-500' },
      { english: 'Blue', portuguese: 'Azul', icon: '🔵', color: 'bg-blue-500' },
      { english: 'Yellow', portuguese: 'Amarelo', icon: '🟡', color: 'bg-yellow-400' },
      { english: 'Green', portuguese: 'Verde', icon: '🟢', color: 'bg-green-500' },
      { english: 'Purple', portuguese: 'Roxo', icon: '🟣', color: 'bg-purple-500' },
      { english: 'Orange', portuguese: 'Laranja', icon: '🟠', color: 'bg-orange-500' },
      { english: 'Pink', portuguese: 'Rosa', icon: '🌸', color: 'bg-pink-400' },
    ],
  },
  {
    id: 'school',
    type: 'school',
    title: '3. What\'s in my Backpack? 🎒',
    subtitle: 'School Objects ✏️',
    description: 'Encontre e guarde os materiais escolares corretos na mochila!',
    colorTheme: 'from-purple-400 to-fuchsia-600',
    vocabList: [
      { english: 'Book', portuguese: 'Livro', icon: '📖' },
      { english: 'Pencil', portuguese: 'Lápis', icon: '✏️' },
      { english: 'Eraser', portuguese: 'Borracha', icon: '🧼' },
      { english: 'Ruler', portuguese: 'Régua', icon: '📏' },
      { english: 'Pencil case', portuguese: 'Estojo', icon: '👝' },
      { english: 'Notebook', portuguese: 'Caderno', icon: '📓' },
    ],
  },
  {
    id: 'animals',
    type: 'animals',
    title: '4. Jungle Adventures 🦁',
    subtitle: 'Animals & Nature 🌳',
    description: 'Descubra os animais da floresta! Clique para ouvir seus nomes!',
    colorTheme: 'from-cyan-400 to-teal-600',
    vocabList: [
      { english: 'Dog', portuguese: 'Cachorro', icon: '🐶' },
      { english: 'Cat', portuguese: 'Gato', icon: '🐱' },
      { english: 'Lion', portuguese: 'Leão', icon: '🦁' },
      { english: 'Monkey', portuguese: 'Macaco', icon: '🐒' },
      { english: 'Bird', portuguese: 'Pássaro', icon: '🐦' },
      { english: 'Butterfly', portuguese: 'Borboleta', icon: '🦋' },
    ],
  },
  {
    id: 'feelings',
    type: 'feelings',
    title: '5. How are you feeling? 😊',
    subtitle: 'Emotions & Expressions 🎭',
    description: 'Como está o seu humor hoje? Escolha a emoção correspondente!',
    colorTheme: 'from-pink-400 to-rose-600',
    vocabList: [
      { english: 'Happy', portuguese: 'Feliz', icon: '😀' },
      { english: 'Sad', portuguese: 'Triste', icon: '😢' },
      { english: 'Angry', portuguese: 'Bravo/a', icon: '😡' },
      { english: 'Tired', portuguese: 'Cansado/a', icon: '😴' },
      { english: 'Excited', portuguese: 'Animado/a', icon: '🤩' },
      { english: 'Scared', portuguese: 'Assustado/a', icon: '😱' },
    ],
  },
  {
    id: 'values',
    type: 'values',
    title: '6. Values for Life ❤️',
    subtitle: 'Espalhe Bons Sentimentos! ✨',
    description: 'Os valores do Quinti! Desembaralhe as letras destes sentimentos!',
    colorTheme: 'from-red-400 to-rose-500',
    vocabList: [
      { english: 'Love', portuguese: 'Amor', icon: '❤️' },
      { english: 'Justice', portuguese: 'Justiça', icon: '⚖️' },
      { english: 'Hope', portuguese: 'Esperança', icon: '🌱' },
      { english: 'Support', portuguese: 'Apoio', icon: '🤝' },
      { english: 'Empathy', portuguese: 'Empatia', icon: '🤟' },
    ],
  },
  {
    id: 'aulas',
    type: 'aulas',
    title: '7. Nossas Aulas 📚',
    subtitle: 'Slides & Materiais 2º Bimestre',
    description: 'Acesse os slides das nossas aulas e baixe o material completo!',
    colorTheme: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'tutor',
    type: 'tutor',
    title: '8. Tutor Quinti 🦉',
    subtitle: 'Seu Amigo para Praticar Inglês!',
    description: 'Converse com o Tutor Quinti e tire todas as suas dúvidas.',
    colorTheme: 'from-indigo-600 to-violet-700',
  },
  {
    id: 'quiz',
    type: 'quiz',
    title: '9. Game Time! 🎮',
    subtitle: 'O Desafio do Super Aluno 🏆',
    description: 'Que tal testarmos o que aprendemos? Responda as perguntas para ganhar sua medalha!',
    colorTheme: 'from-violet-500 to-purple-800',
  },
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    category: 'Greetings',
    question: 'Como dizemos "Bom dia" em inglês?',
    options: ['Good night!', 'Good morning!', 'Good afternoon!', 'Goodbye!'],
    correctAnswer: 'Good morning!',
    hint: 'Começa com "M" e usamos logo que acordamos quando o sol nasce! ☀️',
  },
  {
    id: 'q2',
    category: 'Colors',
    question: 'Qual é a palavra em inglês para a cor "Azul"?',
    options: ['Red', 'Green', 'Blue', 'Yellow'],
    correctAnswer: 'Blue',
    hint: 'É a cor do céu limpo e do oceano profundo! 🔵',
  },
  {
    id: 'q3',
    category: 'School',
    question: 'O que significa a palavra "Book" no material escolar?',
    options: ['Caderno', 'Lápis', 'Borracha', 'Livro'],
    correctAnswer: 'Livro',
    hint: 'É o que nós abrimos para ler histórias maravilhosas! 📖',
  },
  {
    id: 'q4',
    category: 'Animals',
    question: 'Qual desses animais é um "Lion"?',
    options: ['Gato', 'Cachorro', 'Leão', 'Passarinho'],
    correctAnswer: 'Leão',
    hint: 'É o rei da selva, tem uma grande juba que ruge forte! 🦁',
  },
  {
    id: 'q5',
    category: 'Feelings',
    question: 'Se você está sorrindo e dando pulos de alegria, você está:',
    options: ['Sad', 'Angry', 'Happy', 'Tired'],
    correctAnswer: 'Happy',
    hint: 'Como diz o lema: "Sorria, você está aprendendo!". Significa estar feliz! 😀',
  },
  {
    id: 'q6',
    category: 'Values',
    question: 'Qual é a palavra em inglês para "Amor"?',
    options: ['Justice', 'Love', 'Hope', 'Support'],
    correctAnswer: 'Love',
    hint: 'É o sentimento mais bonito do mundo, representado por um coração! ❤️',
  },
];
